# Generated by Django 6.1.1 on 2026-09-14 22:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('pinterest_board_id', models.CharField(blank=True, help_text='Board ID from Pinterest (filled once connected via the API).', max_length=120)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ContentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=90, unique=True)),
                ('color', models.CharField(default='#6366F1', help_text='Hex color used as the category badge/accent (e.g. #6366F1).', max_length=7)),
                ('icon', models.CharField(default='sparkles', help_text='Lucide icon name shown next to the category.', max_length=40)),
            ],
            options={
                'verbose_name_plural': 'Content categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AutomationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False, help_text='Master switch — turn automated posting on or off.')),
                ('pinterest_access_token', models.CharField(blank=True, help_text='Pinterest API access token (stored server-side, never shown in the UI).', max_length=500)),
                ('pinterest_app_id', models.CharField(blank=True, max_length=200)),
                ('posting_frequency', models.CharField(choices=[('1_day', 'Once a day'), ('2_day', 'Twice a day'), ('3_day', 'Three times a day'), ('custom', 'Custom interval')], default='1_day', max_length=10)),
                ('custom_interval_hours', models.PositiveSmallIntegerField(default=6, help_text="Only used when frequency is 'Custom interval'.")),
                ('daily_start_time', models.TimeField(default='09:00', help_text='Earliest time of day a post can go out.')),
                ('daily_end_time', models.TimeField(default='20:00', help_text='Latest time of day a post can go out.')),
                ('post_monday', models.BooleanField(default=True)),
                ('post_tuesday', models.BooleanField(default=True)),
                ('post_wednesday', models.BooleanField(default=True)),
                ('post_thursday', models.BooleanField(default=True)),
                ('post_friday', models.BooleanField(default=True)),
                ('post_saturday', models.BooleanField(default=True)),
                ('post_sunday', models.BooleanField(default=True)),
                ('auto_generate_hashtags', models.BooleanField(default=True)),
                ('only_post_ai_flagged_content', models.BooleanField(default=False, help_text="If on, automation only picks up content marked 'AI generated'.")),
                ('notify_on_failure', models.BooleanField(default=True)),
                ('notification_email', models.EmailField(blank=True, max_length=254)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_board', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pins.board')),
            ],
            options={
                'verbose_name': 'Automation settings',
                'verbose_name_plural': 'Automation settings',
            },
        ),
        migrations.AddField(
            model_name='board',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boards', to='pins.contentcategory'),
        ),
        migrations.CreateModel(
            name='PinContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(help_text='Pinterest pin description (keep it keyword-rich).', max_length=500)),
                ('destination_link', models.URLField(blank=True, help_text='Where the pin should send traffic (blog post, landing page, etc.).')),
                ('image', models.ImageField(upload_to='pins/%Y/%m/')),
                ('alt_text', models.CharField(blank=True, max_length=500)),
                ('hashtags', models.CharField(blank=True, help_text='Space separated, e.g. #AI #Python #WebDev', max_length=300)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('queued', 'Queued for posting'), ('posted', 'Posted'), ('failed', 'Failed')], default='draft', max_length=12)),
                ('scheduled_for', models.DateTimeField(blank=True, help_text='When this pin should go out.', null=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('pinterest_pin_id', models.CharField(blank=True, max_length=120)),
                ('failure_reason', models.CharField(blank=True, max_length=255)),
                ('is_ai_generated', models.BooleanField(default=False, help_text='Flag content whose copy/image was produced by an AI tool.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pins', to='pins.board')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pins', to='pins.contentcategory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure')], max_length=10)),
                ('message', models.CharField(blank=True, max_length=255)),
                ('triggered_by', models.CharField(default='automation', help_text="'automation' or 'manual'", max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='pins.pincontent')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='pincontent',
            index=models.Index(fields=['status', 'scheduled_for'], name='pins_pincon_status_4e5fad_idx'),
        ),
    ]
