# Generated by Django 6.1.1 on 2026-09-15 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationsettings',
            name='default_ai_image_style',
            field=models.CharField(blank=True, default='flat vector illustration, vibrant colors, tech blog aesthetic', help_text='Appended to every AI image prompt to keep a consistent brand look.', max_length=200),
        ),
        migrations.AddField(
            model_name='pincontent',
            name='ai_prompt',
            field=models.CharField(blank=True, help_text="The prompt used to generate this pin's image, if it was AI-generated.", max_length=500),
        ),
    ]
