# Generated by Django 6.1.1 on 2026-09-20 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0002_automationsettings_default_ai_image_style_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automationsettings',
            name='daily_end_time',
        ),
        migrations.RemoveField(
            model_name='automationsettings',
            name='daily_start_time',
        ),
        migrations.AddField(
            model_name='automationsettings',
            name='afternoon_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='automationsettings',
            name='afternoon_end',
            field=models.TimeField(default='15:00'),
        ),
        migrations.AddField(
            model_name='automationsettings',
            name='afternoon_start',
            field=models.TimeField(default='13:00'),
        ),
        migrations.AddField(
            model_name='automationsettings',
            name='evening_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='automationsettings',
            name='evening_end',
            field=models.TimeField(default='20:00'),
        ),
        migrations.AddField(
            model_name='automationsettings',
            name='evening_start',
            field=models.TimeField(default='18:00'),
        ),
        migrations.AddField(
            model_name='automationsettings',
            name='morning_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='automationsettings',
            name='morning_end',
            field=models.TimeField(default='10:00'),
        ),
        migrations.AddField(
            model_name='automationsettings',
            name='morning_start',
            field=models.TimeField(default='08:00'),
        ),
    ]
