# Generated by Django 6.1.1 on 2026-09-20 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0003_remove_automationsettings_daily_end_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPostSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('window', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening')], max_length=10)),
                ('planned_time', models.TimeField(help_text="Randomly chosen once per day, within that window's range.")),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_slots', to='pins.pincontent')),
            ],
            options={
                'ordering': ['date', 'planned_time'],
                'unique_together': {('date', 'window')},
            },
        ),
    ]
