# Generated by Django 6.1.1 on 2026-09-21 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0004_dailypostslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationsettings',
            name='overlay_title_on_image',
            field=models.BooleanField(default=False, help_text="If on, each pin's title is overlaid as text on its image right before posting (tries Gemini first if configured, always falls back to a local text overlay)."),
        ),
    ]
